import json
plans = json.load(open('plans.json'))
def enc(cells, cx, cy): return ";".join(f"{x-cx},{y-cy}" for x, y in cells)
out = []
for p in plans:
    cx, cy = p["centre"]
    parts = [f"seed={p['seed']}"]
    parts.append("fixed=" + "|".join(f"{n}:{enc(cs, cx, cy)}" for n, cs in sorted(p["fixed"].items())))
    parts.append("base=" + enc(p["base"], cx, cy))
    parts.append("offices=" + "|".join(enc(o["cells"], cx, cy) + "/" + enc(o["hall"], cx, cy)
                                      + "/" + str(o["ring"]) for o in p["offices"]))
    out.append("\n".join(parts))
def lit(t):
    inner = "\n".join("    " + ln for ln in t.split("\n"))
    return '    """\n' + inner + '\n    """'
body = ",\n".join(lit(t) for t in out)
src = '''// Floor plans, baked. Generated by floor/bake.py — do not edit by hand.
//
// Each plan is one station's whole floor: the fixed blocks, the hallway that is lit before anything opens,
// and a hundred offices in radial order, each carrying the run of hallway that first reaches it. Lighting
// them in order keeps the floor connected at every step, which is checked when a plan is loaded.

enum BakedPlans {
    static let all: [String] = [
%s
    ]
}
''' % body
open('/tmp/claude-502/floor/BakedPlans.swift','w').write(src)
print(len(src), "bytes,", len(out), "plans")
